### ISSUE TITLE
PCA showing the relationship between sex, treatment, tissue

### ISSUE THREAD

**Issue by raynamharris** [macmanes-lab/DoveParentsRNAseq#4]
As a first pass, I have created this multi-dimensional scaling (MDS) plot of all the samples. Male and female hypothalamus and pituitary samples cluster together while female and male gonads form distinct clusters. 

There may be one outlier sample: female_pituitary_control.NYNO

These two plots show the same data but are colored differently. 
![plotMDS-colored-1](https://user-images.githubusercontent.com/7544197/54642803-782ddc80-4a63-11e9-8d3b-849bd668f6d2.png)
![plotMDS-colored-3](https://user-images.githubusercontent.com/7544197/54642813-7bc16380-4a63-11e9-85cd-f7ae22138cd7.png)

See https://github.com/macmanes-lab/DoveParentsRNAseq/blob/master/analysis/01_limma_all.md for detailed analysis

**Comment by raynamharris** [comment]
Here is a PCA I created on **non-normalized** counts, but this looks a little funny. I'm tempted to use DESeq to normalize all the data and then do the PCA. I want to have more control over the plot than is allowed by limma.... But another alternative is to export the limma-normalized data and then use ggplot2.


![pca-5](https://user-images.githubusercontent.com/7544197/56697586-e76ea000-66a3-11e9-8e86-137fc020b02f.png)

See  https://github.com/macmanes-lab/DoveParentsRNAseq/blob/master/analysis/01_pca_all.md

**Comment by macmanes** [comment]
I think this is the lack of normalization making it look funny, potentially.

______________________________________________
Matthew MacManes, Ph.D.
University of New Hampshire  I  Assistant Professor of Genome Enabled Biology
Department of Molecular, Cellular, & Biomedical Sciences
Durham, NH  03824<x-apple-data-detectors://1/0>
Phone: 603-862-4052<tel:603-862-4052>  I  Twitter: @macmanes | Web: genomebio.org<http://genomebio.org/>
Office: 434 Gregg Hall | Laboratory: 437 Gregg Hall


On Apr 24, 2019, at 18:22, Rayna M Harris <notifications@github.com<mailto:notifications@github.com>> wrote:

Caution - External Email
________________________________

Here is a PCA I created on non-normalized counts, but this looks a little funny. I'm tempted to use DESeq to normalize all the data and then do the PCA. I want to have more control over the plot than is allowed by limma.... But another alternative is to export the limma-normalized data and then use ggplot2.

[pca-5]<https://urldefense.proofpoint.com/v2/url?u=https-3A__user-2Dimages.githubusercontent.com_7544197_56697586-2De76ea000-2D66a3-2D11e9-2D8e86-2D137fc020b02f.png&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=lFmSBplGfvpPNKk6W2tN6-UcUrgjlsdpj7JuHtA6g_Y&m=cCrYUhiIfSxP54xUfUnRBDTTudsx7DiNkk1Xj3HiZcg&s=GkXhZHYnjYXTpHDnLE_HBtwfC9ZUwnZmJoqnKrBGfnM&e=>

See https://github.com/macmanes-lab/DoveParentsRNAseq/blob/master/analysis/01_pca_all.md<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_macmanes-2Dlab_DoveParentsRNAseq_blob_master_analysis_01-5Fpca-5Fall.md&d=DwMFaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=lFmSBplGfvpPNKk6W2tN6-UcUrgjlsdpj7JuHtA6g_Y&m=cCrYUhiIfSxP54xUfUnRBDTTudsx7DiNkk1Xj3HiZcg&s=X9eAYENv-sTCs6-T8TzhhLMd5pX88gGE3BrBw6OHwuw&e=>

**Comment by raynamharris** [comment]
Yes, indeed. Lack of normalizations makes it look funny. I still haven't gotten DESeq to run overnight, but here are some edgeR normalized plots. I still think this one looks funny too. This is all 500+ samples from the characterization study.

![normalized-2](https://user-images.githubusercontent.com/7544197/56760933-155dee00-6751-11e9-8814-02d3305cd6d3.png)

More at https://github.com/macmanes-lab/DoveParentsRNAseq/blob/master/analysis/01_pca_all.md

**Comment by raynamharris** [comment]
I finally figured out that this funny-looking PCA plot is actually driven by epression of a few genes! Here is it colored by treatment with the genes that drive that PCA on the right. Shows that _COX1_ in the hypothalamus of controls and _PRL_ in the pituitary of inc.d17, hatch, and n5.  

![pca-3](https://user-images.githubusercontent.com/7544197/67113224-cdfb6c00-f18d-11e9-8827-28d8fe5bb62e.png)

**Comment by raynamharris** [comment]
And a tSNE plot really highlight differences between sex, tissue, and treatment! The same data is ploted side by side, but with tissue colored on the left and treatment colored on the right.

![tSNE-2](https://user-images.githubusercontent.com/7544197/67113282-f08d8500-f18d-11e9-8dc6-4bcd84a6bdf6.png)

**Comment by raynamharris** [comment]
and here's a combination of pca and tsne. i think this is close to a manuscript-worthly figure which highlights that there aren't many sex differences (except for in the gonad) and that hypothalmaus controls sample are very different from the rest and that pituitary samples cluster into those why high _PRL_ and low _PRL_.

The first figure includes the legend for readability, but the second has the legend removed, which we could do if we explain the colors in the legend.

## with legend
![pca tSNE-1](https://user-images.githubusercontent.com/7544197/67114453-c25d7480-f190-11e9-8e3f-9c89606819f4.png)

## without legend
![pca tSNE-2](https://user-images.githubusercontent.com/7544197/67114455-c25d7480-f190-11e9-9d68-514b15e7d41b.png)

**Comment by raynamharris** [comment]
and here's a combination of pca and tsne. i think this is close to a manuscript-worthy figure which highlights that there aren't many sex differences (except for in the gonad) and that hypothalamus controls sample are very different from the rest and that pituitary samples cluster into those why high PRL and low PRL.

![pca tSNE-3](https://user-images.githubusercontent.com/7544197/67116008-5da41900-f194-11e9-8d76-7b80fa8f7bcb.png)

**Comment by raynamharris** [comment]
Currently showing a tsne analysis in figure 1 that provides a nice overview of the data

![fig1-1](https://user-images.githubusercontent.com/7544197/92035318-5ee62200-ed23-11ea-8292-85a8e7040f41.png)
